import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterSection from "@/components/FooterSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CORDON",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.svg" sizes="any" />
      <body className={inter.className}>
        <div className="min-h-[100vh] flex flex-col justify-between">
          <div>{children}</div>
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
